from pathlib import Path
from typing import Dict, Any

class MarkdownReportGenerator:
    """Generates clean Markdown reports for GitHub PRs and documentation summaries."""

    @staticmethod
    def generate(data: Dict[str, Any], output_path: str = "reports/evaluation_report.md") -> None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        md_content = f"""# ⚡ AITestKit Benchmark Summary Report

Automated Evaluation Report generated by **AITestKit Core Engine**.

---

## 📊 Summary Metrics

| Evaluation Suite | Score / Status |
| :--- | :--- |
"""
        for section, metrics in data.items():
            md_content += f"| **{section.upper()}** | `{metrics}` |\n"

        md_content += """
---
*Generated using [AITestKit](https://github.com/aitestkit/aitestkit)*
"""

        with open(path, "w", encoding="utf-8") as f:
            f.write(md_content)